module Example exposing (suite)

import Expect exposing (Expectation, equal)
import Fuzz exposing (Fuzzer, int, list, string)
import Test exposing (..)
import Tokipona exposing (translate, translatePona)


suite : Test
suite =
    describe "Tokipona test suite"
        [ describe "limit"
            [ test "toto" <| \_ -> translate "toto" |> equal "[ERROR: 'toto' is not a valid word]"
            , test "support spaces" <| \_ -> translate "  mi " |> equal "I; me, we, us"
            , test "support spaces simple" <| \_ -> translatePona "  mi " |> equal "I"
            , test "empty phrase" <| \_ -> translate "" |> equal ""
            , test "empty phrase simple" <| \_ -> translatePona "" |> equal ""
            ]
        , describe
            "lesson #3 http://tokipona.net/tp/janpije/okamasona3.php"
            [ test "jan" <| \_ -> translate "jan" |> equal "people; human, being, person, somebody, anybody"
            , test "mi" <| \_ -> translate "mi" |> equal "I; me, we, us"
            , test "moku" <| \_ -> translate "moku" |> equal "to ingest; to eat, to drink, to consume, to swallow"
            , test "sina" <| \_ -> translate "sina" |> equal "you"
            , test "suli" <| \_ -> translate "suli" |> equal "big; heavy, large, long, tall; important; adult"
            , test "suno" <| \_ -> translate "suno" |> equal "sun; light, brightness, glow, radiance, shine; light source"
            , test "telo" <| \_ -> translate "telo" |> equal "water; liquid, fluid, wet substance; beverage; juice, sauce"
            , test "pona" <| \_ -> translate "pona" |> equal "good; simple, positive, nice, correct, right, useful; friendly, peaceful"
            , test "li" <| \_ -> translate "li" |> equal "separates some subjects (especially third-person) from the verb"
            , test "mi pona" <| \_ -> translate "mi pona" |> equal "I; me, we, us / ('good; simple, positive, nice, correct, right, useful; friendly, peaceful' as a verb or being...)"
            , test "sina suli" <| \_ -> translate "sina suli" |> equal "you / ('big; heavy, large, long, tall; important; adult' as a verb or being...)"
            , test "mi moku" <| \_ -> translate "mi moku" |> equal "I; me, we, us / to ingest; to eat, to drink, to consume, to swallow"
            , test "sina pona" <| \_ -> translate "sina pona" |> equal "you / ('good; simple, positive, nice, correct, right, useful; friendly, peaceful' as a verb or being...)"
            , test "telo li pona" <| \_ -> translate "telo li pona" |> equal "water; liquid, fluid, wet substance; beverage; juice, sauce / ('good; simple, positive, nice, correct, right, useful; friendly, peaceful' as a verb or being...)"
            , test "suno li suli" <| \_ -> translate "suno li suli" |> equal "sun; light, brightness, glow, radiance, shine; light source / ('big; heavy, large, long, tall; important; adult' as a verb or being...)"
            , test "moku li pona" <| \_ -> translate "moku li pona" |> equal "food; meal / ('good; simple, positive, nice, correct, right, useful; friendly, peaceful' as a verb or being...)"
            ]
        , describe
            "lesson #3 Simple http://tokipona.net/tp/janpije/okamasona3.php"
            [ test "jan" <| \_ -> translatePona "jan" |> equal "people"
            , test "mi" <| \_ -> translatePona "mi" |> equal "I"
            , test "moku" <| \_ -> translatePona "moku" |> equal "to ingest"
            , test "sina" <| \_ -> translatePona "sina" |> equal "you"
            , test "suli" <| \_ -> translatePona "suli" |> equal "big"
            , test "suno" <| \_ -> translatePona "suno" |> equal "sun"
            , test "telo" <| \_ -> translatePona "telo" |> equal "water"
            , test "pona" <| \_ -> translatePona "pona" |> equal "good"
            , test "li" <| \_ -> translatePona "li" |> equal "separates some subjects (especially third-person) from the verb"
            , test "mi pona" <| \_ -> translatePona "mi pona" |> equal "I / ('good' as a verb or being...)"
            , test "sina suli" <| \_ -> translatePona "sina suli" |> equal "you / ('big' as a verb or being...)"
            , test "mi moku" <| \_ -> translatePona "mi moku" |> equal "I / to ingest"
            , test "sina pona" <| \_ -> translatePona "sina pona" |> equal "you / ('good' as a verb or being...)"
            , test "telo li pona" <| \_ -> translatePona "telo li pona" |> equal "water / ('good' as a verb or being...)"
            , test "suno li suli" <| \_ -> translatePona "suno li suli" |> equal "sun / ('big' as a verb or being...)"
            , test "moku li pona" <| \_ -> translatePona "moku li pona" |> equal "food / ('good' as a verb or being...)"
            , test "jan li pona" <| \_ -> translatePona "jan li pona" |> equal "people / ('good' as a verb or being...)"
            , test "mi suli" <| \_ -> translatePona "mi suli" |> equal "I / ('big' as a verb or being...)"
            , test "telo li suli" <| \_ -> translatePona "telo li suli" |> equal "water / ('big' as a verb or being...)"
            , test "jan li moku" <| \_ -> translatePona "jan li moku" |> equal "people / to ingest"
            ]
        , describe
            "lesson #4 http://tokipona.net/tp/janpije/okamasona4.php"
            [ test "ilo" <| \_ -> translate "ilo" |> equal "tool; implement, machine, device; thing used for a specific purpose"
            , test "kili" <| \_ -> translate "kili" |> equal "fruit; vegetable, mushroom"
            , test "ni" <| \_ -> translate "ni" |> equal "this, that"
            , test "ona" <| \_ -> translate "ona" |> equal "he, she, it"
            , test "pipi" <| \_ -> translate "pipi" |> equal "bug; insect, ant, spider"
            , test "ma" <| \_ -> translate "ma" |> equal "area; earth, land; outdoor area; world; region, country, territory; soil"
            , test "ijo" <| \_ -> translate "ijo" |> equal "something; anything, stuff, thing, object"
            , test "jo" <| \_ -> translate "jo" |> equal "to have; to carry, contain, hold"
            , test "lukin" <| \_ -> translate "lukin" |> equal "to look; to pay attention, to examine, to observe, to read, to watch"
            , test "oko" <| \_ -> translate "oko" |> equal "eye"
            , test "pakala" <| \_ -> translate "pakala" |> equal "to screw up; to fall apart, to break"
            , test "unpa" <| \_ -> translate "unpa" |> equal "to have sex"
            , test "wile" <| \_ -> translate "wile" |> equal "to want; need, wish, have to, must, will, should"
            , test "e" <| \_ -> translate "e" |> equal "introduces direct object"
            , test "mi moku e kili" <| \_ -> translate "mi moku e kili" |> equal "I; me, we, us / to ingest; to eat, to drink, to consume, to swallow / fruit; vegetable, mushroom"
            , test "ona li lukin e pipi" <| \_ -> translate "ona li lukin e pipi" |> equal "he, she, it / to see; to look at, to watch, to read / bug; insect, ant, spider"
            , test "ona li pona e ilo" <| \_ -> translate "ona li pona e ilo" |> equal "he, she, it / to fix; to improve, to repair, to make good / tool; implement, machine, device; thing used for a specific purpose"
            , test "mi pona e ijo" <| \_ -> translate "mi pona e ijo" |> equal "I; me, we, us / to fix; to improve, to repair, to make good / something; anything, stuff, thing, object"
            , test "mi wile lukin e ma" <| \_ -> translate "mi wile lukin e ma" |> equal "I; me, we, us / want; need, wish, have to, must, will, should / to see; to look at, to watch, to read / area; earth, land; outdoor area; world; region, country, territory; soil"
            , test "mi wile pakala e sina" <| \_ -> translate "mi wile pakala e sina" |> equal "I; me, we, us / want; need, wish, have to, must, will, should / to screw up; to ruin, to break, to hurt, to injure, to damage, to destroy / you"
            , test "pipi li lukin li unpa" <| \_ -> translate "pipi li lukin li unpa" |> equal "bug; insect, ant, spider / to look; to pay attention, to examine, to observe, to read, to watch / and / to have sex"
            , test "pipi li lukin e mi li unpa e sina" <| \_ -> translate "pipi li lukin e mi li unpa e sina" |> equal "bug; insect, ant, spider / to see; to look at, to watch, to read / I; me, we, us / and / to have sex with; to sleep with, to fuck / you"
            , test "pipi li wile lukin e mi li wile unpa e sina" <| \_ -> translate "pipi li wile lukin e mi li wile unpa e sina" |> equal "bug; insect, ant, spider / want; need, wish, have to, must, will, should / to see; to look at, to watch, to read / I; me, we, us / and / want; need, wish, have to, must, will, should / to have sex with; to sleep with, to fuck / you"
            ]
        , describe
            "lesson #4 Simple http://tokipona.net/tp/janpije/okamasona4.php"
            [ test "ilo" <| \_ -> translatePona "ilo" |> equal "tool"
            , test "kili" <| \_ -> translatePona "kili" |> equal "fruit"
            , test "ni" <| \_ -> translatePona "ni" |> equal "this, that"
            , test "ona" <| \_ -> translatePona "ona" |> equal "he, she, it"
            , test "pipi" <| \_ -> translatePona "pipi" |> equal "bug"
            , test "ma" <| \_ -> translatePona "ma" |> equal "area"
            , test "ijo" <| \_ -> translatePona "ijo" |> equal "something"
            , test "jo" <| \_ -> translatePona "jo" |> equal "to have"
            , test "lukin" <| \_ -> translatePona "lukin" |> equal "to look"
            , test "oko" <| \_ -> translatePona "oko" |> equal "eye"
            , test "pakala" <| \_ -> translatePona "pakala" |> equal "to screw up"
            , test "unpa" <| \_ -> translatePona "unpa" |> equal "to have sex"
            , test "wile" <| \_ -> translatePona "wile" |> equal "to want"
            , test "e" <| \_ -> translatePona "e" |> equal "introduces direct object"
            , test "mi moku e kili" <| \_ -> translatePona "mi moku e kili" |> equal "I / to ingest / fruit"
            , test "ona li lukin e pipi" <| \_ -> translatePona "ona li lukin e pipi" |> equal "he, she, it / to see / bug"
            , test "ona li pona e ilo" <| \_ -> translatePona "ona li pona e ilo" |> equal "he, she, it / to fix / tool"
            , test "mi pona e ijo" <| \_ -> translatePona "mi pona e ijo" |> equal "I / to fix / something"
            , test "mi wile lukin e ma" <| \_ -> translatePona "mi wile lukin e ma" |> equal "I / want / to see / area"
            , test "mi wile pakala e sina" <| \_ -> translatePona "mi wile pakala e sina" |> equal "I / want / to screw up / you"
            , test "pipi li lukin li unpa" <| \_ -> translatePona "pipi li lukin li unpa" |> equal "bug / to look / and / to have sex"
            , test "pipi li lukin e mi li unpa e sina" <| \_ -> translatePona "pipi li lukin e mi li unpa e sina" |> equal "bug / to see / I / and / to have sex with / you"
            , test "pipi li wile lukin e mi li wile unpa e sina" <| \_ -> translatePona "pipi li wile lukin e mi li wile unpa e sina" |> equal "bug / want / to see / I / and / want / to have sex with / you"
            ]
        ]
